parent = "/some/parent/*"
arr = [
	"one",
	"two",
	"three"
]

[[route]]
path       = "/some/path"
controller = "some-controller"
verb       = "GET"
method     = "SomeMethod"

[[route]]
path       = "/random/path/:id"
controller = "random-controller"
verb       = "GET"
method     = "RandomMethod"
